apiVersion: batch/v1
kind: Job
metadata:
  namespace: kubefill
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    metadata:
      name: ""
    spec:
      serviceAccountName: eks-worker-service-account
      restartPolicy: Never
      nodeSelector:
        node-group: c5
      volumes:
        - name: gitconfig
          secret:
            secretName: gitconfig
            defaultMode: 0600
        - name: oxford-id-rsa
          secret:
            secretName: oxford-id-rsa
            defaultMode: 0600
      containers:
        - name: enterprise-wc-percy-tests
          image: hookandloop/enterprise-wc-percy-tests:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "14"
              memory: "28G"
            limits:
              cpu: "14"
              memory: "30G"
          volumeMounts:
            - name: gitconfig
              readOnly: true
              mountPath: /usr/src/gitconfig
            - name: oxford-id-rsa
              readOnly: true
              mountPath: /usr/src/id_rsa
          env:
            - name: GITLAB_PRIVATE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: gitlab-enterprise-private-token
                  key: token
            - name: GITLAB_BASE_URL
              value: "oxford.awsdev.infor.com"
            - name: GITLAB_PROJECT_ID
              value: "26500"
            - name: REPO_OWNER_NAME
              value: "ssh://git@oxfordssh.awsdev.infor.com:7999/infor-design/enterprise-wc.git"
            - name: PERCY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: enterprise-wc-percy-token
                  key: token
            - name: NODE_OPTIONS
              value: "--max-old-space-size=8192"
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                    cp /usr/src/gitconfig/gitconfig /root/.gitconfig &&
                    cp /usr/src/id_rsa/key /root/.ssh/id_rsa
