// Import All Components Used in the Page
import IdsLoader from '../src/ids-loader/ids-loader';
import IdsButton from '../src/ids-button/ids-button';
import IdsCheckbox from '../src/ids-checkbox/ids-checkbox';
import IdsSwitch from '../src/ids-switch/ids-switch';
import IdsToggleButton from '../src/ids-toggle-button/ids-toggle-button';
import IdsMenuButton from '../src/ids-menu-button/ids-menu-button';
import IdsText from '../src/ids-text/ids-text';
import IdsIcon from '../src/ids-icon/ids-icon';
import IdsPopup from '../src/ids-popup/ids-popup';
import IdsTag from '../src/ids-tag/ids-tag';
import IdsLayoutGrid from '../src/ids-layout-grid/ids-layout-grid';
import IdsLayoutGridCell from '../src/ids-layout-grid/ids-layout-grid-cell';
import IdsInput from '../src/ids-input/ids-input';
import IdsTriggerField from '../src/ids-trigger-field/ids-trigger-field';
import IdsTriggerButton from '../src/ids-trigger-button/ids-trigger-button';
import IdsExpandableArea from '../src/ids-expandable-area/ids-expandable-area';
import IdsAccordion from '../src/ids-accordion/ids-accordion';
import IdsRadio from '../src/ids-radio/ids-radio';
import IdsRenderLoopMixin from '../src/ids-render-loop/ids-render-loop-mixin';
import IdsTextarea from '../src/ids-textarea/ids-textarea';
import IdsUpload from '../src/ids-upload/ids-upload';
import IdsAlert from '../src/ids-alert/ids-alert';
import IdsBadge from '../src/ids-badge/ids-badge';
import IdsBlockGrid from '../src/ids-block-grid/ids-block-grid';
import IdsBlockGridItem from '../src/ids-block-grid/ids-block-grid-item';

// Import Example Code

import './ids-menu-button/example';
import './ids-checkbox/example';
import './ids-icon/example';
import './ids-input/example';
import './ids-input/test-validation-message';
import './ids-popup/example';
import './ids-render-loop/example';
import './ids-toggle-button/example';
import './ids-radio/example';
import './ids-alert/example';
import './ids-button/index';
import './ids-menu-button/index';
import './ids-checkbox/example';
import './ids-icon/index';
import './ids-input/example';
import './ids-input/test-validation-message';
import './ids-popup/index';
import './ids-render-loop/index';
import './ids-toggle-button/index';
import './ids-trigger-field/index';
import './ids-radio/example';
import './ids-alert/index';
import './ids-badge/index';
import './ids-textarea/example';
import './ids-block-grid/index';
