// Import All Components Used in the Page
import IdsLoader from '../src/ids-loader/ids-loader';
import IdsButton from '../src/ids-button/ids-button';
import IdsCheckbox from '../src/ids-checkbox/ids-checkbox';
import IdsSwitch from '../src/ids-switch/ids-switch';
import IdsToggleButton from '../src/ids-toggle-button/ids-toggle-button';
import IdsMenuButton from '../src/ids-menu-button/ids-menu-button';
import IdsText from '../src/ids-text/ids-text';
import IdsHyperlink from '../src/ids-hyperlink/ids-hyperlink';
import IdsIcon from '../src/ids-icon/ids-icon';
import IdsPopup from '../src/ids-popup/ids-popup';
import IdsToolbar, { IdsToolbarSection, IdsToolbarMoreActions } from '../src/ids-toolbar/ids-toolbar';
import IdsProgress from '../src/ids-progress/ids-progress';
import IdsUploadAdvanced from '../src/ids-upload-advanced/ids-upload-advanced';
import IdsTag from '../src/ids-tag/ids-tag';
import IdsLayoutGrid from '../src/ids-layout-grid/ids-layout-grid';
import IdsLayoutGridCell from '../src/ids-layout-grid/ids-layout-grid-cell';
import IdsInput from '../src/ids-input/ids-input';
import IdsTriggerField from '../src/ids-trigger-field/ids-trigger-field';
import IdsTriggerButton from '../src/ids-trigger-field/ids-trigger-button';
import IdsExpandableArea from '../src/ids-expandable-area/ids-expandable-area';
import IdsAccordion from '../src/ids-accordion/ids-accordion';
import IdsRadio from '../src/ids-radio/ids-radio';
import IdsRenderLoopMixin from '../src/ids-mixins/ids-render-loop-mixin';
import IdsTextarea from '../src/ids-textarea/ids-textarea';
import IdsUpload from '../src/ids-upload/ids-upload';
import IdsAlert from '../src/ids-alert/ids-alert';
import IdsBadge from '../src/ids-badge/ids-badge';
import IdsBlockGrid from '../src/ids-block-grid/ids-block-grid';
import IdsBlockGridItem from '../src/ids-block-grid/ids-block-grid-item';
import IdsCounts from '../src/ids-counts/ids-counts';
import IdsContainer from '../src/ids-container/ids-container';
import IdsThemeSwitcher from '../src/ids-theme-switcher/ids-theme-switcher';
import IdsRating from '../src/ids-rating/ids-rating';
import IdsWizard, { IdsWizardStep } from '../src/ids-wizard';
import IdsSpinbox from '../src/ids-spinbox';
import IdsModal, { IdsOverlay } from '../src/ids-modal';
import IdsTabs, { IdsTab } from '../src/ids-tabs';

// Import Example Code

import './ids-menu-button/example';
import './ids-icon/example';
import './ids-popup/example';
import './ids-render-loop/example';
import './ids-toggle-button/example';
import './ids-alert/example';
import './ids-button/index';
import './ids-menu-button/index';
import './ids-checkbox/example';
import './ids-icon/index';
import './ids-input/example';
import './ids-input/test-validation-message';
import './ids-mask/example';
import './ids-modal/example';
import './ids-progress/example';
import './ids-upload-advanced/example';
import './ids-popup/index';
import './ids-render-loop/index';
import './ids-toggle-button/index';
import './ids-trigger-field/index';
import './ids-radio/example';
import './ids-alert/index';
import './ids-badge/index';
import './ids-textarea/example';
import './ids-block-grid/index';
import './ids-counts/index';
import './ids-wizard/index';
import './ids-spinbox/index';
import './ids-tabs/index';
