# Stale Bot
# See Docs: https://docs.github.com/en/actions/managing-issues-and-pull-requests/closing-inactive-issues#introduction
# Runs every day at 1:30 UTC
name: Close inactive issues
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9.0.0
        with:
          days-before-issue-stale: 340
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contribution."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
